# Generated by Django 4.0.6 on 2022-07-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labels',
            old_name='name',
            new_name='label',
        ),
    ]
