# Generated by Django 4.0.6 on 2022-07-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-is_pinned', '-id']},
        ),
    ]
